spring:
  application:
    name: demo-provider

dubbo:
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: defaultRegistry
  protocol:
    port: 20882
    name: dubbo
    status: server
    id: dubbo
  application:
    name: demo-provider
    id: demo-provider
    qosEnable: true
    qosPort: 22223
  scan:
    basePackages: org.hongxi.whatsmars.dubbo.demo.provider.service

registry:
  other:
    protocol: zookeeper
    address: 127.0.0.1:2181
    id: other
